name: Build Constitution PDF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: theorangeone/docker-pandoc

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build document
      run: make -C latex

    - name: Store built PDF
      uses: actions/upload-artifact@v3.1.3
      with:
        name: constitution.pdf
        path: latex/constitution.pdf
